# _config.yml
header_pages:
  - index.md
# 其他配置...
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# 如果您有自定義 CSS，通常需要這樣指定：
sass:
  sass_dir: _sass
  style:    :compressed
# 或者直接引入CSS
# 如果您的主題有 head.html 或 default.html 佈局，您需要在裡面添加 <link rel="stylesheet" href="{{ '/assets/css/style.css' | relative_url }}">